project:
  type: book
  output-dir: docs

book:
  title: "Análisis de Datos con R Aplicado a Políticas Públicas"
  reader-mode: true
  author: "Gabriel Duarte Zuñiga"
  date: last-modified
  date-format: long
  page-footer:
    left: |
      Este libro está diseñado para ser utilizado como material de apoyo de los cursos
      de Ciencia de Datos para Políticas Públicas en los que
      participa como profesor Gabriel Duarte Z.
      Cualquier error es de exclusiva responsabilidad del autor.
    right: |
      Este libro fue construido mediante <a href="https://quarto.org/">Quarto</a>.
  cover-image: portada1.png
  # favicon: cover.jpg
  # site-url: https://r4ds.hadley.nz/
  # repo-url: https://github.com/hadley/r4ds/
  # repo-branch: main
  # repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: p0_intror.qmd
      chapters:
        - c0_instr.qmd
        - c0_basics.qmd
    - part: p1_nivelacion.qmd
      chapters:
        - c0_descriptivo.qmd
        - c0_probabilidad.qmd
    - part: p2_tidyverse.qmd
      chapters:
        - c1_importar.qmd
        - c2_transformar.qmd
        - c3_visualizar.qmd
        - c4_comunicar.qmd
    - part: p3_estadistica-aplicada.qmd
      chapters:
        - c5_bootstrap.qmd
        - c6_inferencia.qmd
        - c7_regresion1.qmd
        - c8_regresion2.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    # code-link: true
    code-line-numbers: true
    # code-tools: true
    number-depth: 4
    toc-depth: 4
    code-summary: "Quiero ver el código"
    code-block-border-left: "#31BAE9"
    css:
    - include/webex.css
    include-after-body: include/webex.js
    author-meta: "Gabriel Duarte Zuñiga"
    # include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

webr: 
  show-startup-message: true     # Display status of webR initialization
#  show-header-message: false     # Check to see if COOP&COEP headers are set for speed.
# packages: ['tidyverse', 'scales'] # Pre-install dependencies
#  base-url: ''                   # Base URL used for specifying where R WebAssembly binaries should be located
#  home-dir: '/home/rstudio'      # Customize where the working directory is
#  channel-type: 'post-message'   # Specify communication channel
#  service-worker-url: ''         # URL from where to load JavaScript worker scripts when loading webR with the ServiceWorker communication channel.

# Attach webR to every page
filters:
  - webr

