# ¡Bienvenid\@! {.unnumbered}

Bienvenid\@ a este recurso en línea gratuito para aprender a programar en `R` desde cero. A diferencia de muchos libros físicos y online, este material está diseñado para **aprender haciendo**, del cual destaco dos principales ventajas:

1.  Podrás ejecutar **código en línea** sin instalar nada en tu computador.
2.  La mayoría de los datos utilizados corresponden a información pública de Chile que están puestas en contexto para poder responder problemáticas reales en el ámbito políticas públicas en Chile, especialmente en temas prioritarios como la seguridad ciudadana. Esto permite acercar la ciencia de datos a problemas concretos del ámbito público, utilizando principalmente datasets abiertos y pudiendo reproducir análisis y resultados concretos.

Cuando comencé a escribir este libro tenía dos objetivos claros. Primero, crear un recurso práctico para mis clases de análisis de datos que realizo en la Universidad Adolfo Ibáñez y la Universidad San Sebastián utilizando medios online. Segundo, aportar a la oferta de materiales gratuitos para aprender R, pero con un enfoque en la resolución de problemas concretos que sirvan tanto a estudiantes como a profesionales del sector público en donde se apliquen ejemplos reales y relevantes para las políticas públicas.

Esto bajo la visión de ayudar en la formación de futuros analistas en este ámbito y enriquecer el capital humano y conocimiento de quienes ya se encuentren insertos en el mundo público o tengan aspiraciones de hacerlo.

Desde que conocí el lenguaje de programación `R` en el año 2020, he
buscado constantemente soluciones que ayuden a responder preguntas urgentes del
sector público. Aunque existen muchos recursos valiosos, a menudo los analistas
necesitamos respuestas rápidas y fundamentadas, algo difícil de lograr usando
solo herramientas tradicionales como Excel, en donde la reproducibilidad y la
trazabilidad suelen quedar en segundo plano.

Siendo transparente, estoy lejos de creer que `R` es *el* medio correcto para resolver todas las tareas o problemáticas que los empleados púbicos enfrentan. Muchas veces, la gestión pública y el rol del analista que insuma la toma decisiones en la materia, requiere simplemente de habilidades como la redacción de informes o producción de tablas, las cuales dependiendo de su extensión y profundidad, pueden realizarse de manera más eficientemente directamente desde un documento de Microsoft Word o Excel.

Sin embargo, para tareas que exigen reproducibilidad, robustez estadística y escalabilidad, dominar herramientas de análisis de datos avanzadas como `R` o `Python` es clave. Y el hecho de que sean de fuente abierta, facilita aún más el acceso a ellas. En este sentido, si el objetivo final es mejorar el bien común mediante la implementación de políticas públicas pertinentes y bien diseñadas, considero menester que quienes trabajamos con información variada podamos perfeccionar nuestras habilidades para surfear las olas en las que navega el quehacer público.

Por ejemplo, en un proyecto de instalación de cámaras con presupuesto limitado, antes de preguntar *dónde ubicarlas* es fundamental definir su objetivo: ¿reducir delitos?, ¿aumentar la percepción de seguridad?, ¿generar evidencia para investigaciones? Según lo que busque lograr, los criterios para decidir la ubicación cambiarán y probablemente tendrán impactos distintos. Una vez claro el objetivo, herramientas como `R` permiten identificar zonas con mayor concentración delictual y tomar decisiones mejor informadas.

En este sentido, no basta con aplicar modelos estadísticos, sino que resulta esencial es formular bien las preguntas correctas y fijar objetivos coherentes con el diseño de la politica pública. Siguiendo con la analogía del *surf*, `R` sería la tabla para surfear las olas, pero la elección de qué ola se debe tomar y cuál se debe dejar pasar, depende del criterio del analista, del diseño de la política, de la disponibilidad de información y tantas otros elementos a considerar en la práctica.

A medida que los estudiantes se adentren en el uso de `R`, se darán cuenta de que detrás de este software hay una extensa comunidad que impulsa su desarrollo. Consecuentemente, existen muchos recursos gratuitos y en línea para aprender `R`. Sin embargo, esa misma abundancia puede resultar abrumadora para quienes recién comienzan, pues surgen preguntas como:

-   *¿Qué recurso debería elegir?*

-   *¿Por qué no entiendo todo lo que hace este código?*

-   *¿Cómo sé si este material es adecuado para mi nivel?*

-   *¿En qué momento voy a poder aplicar esto a mi trabajo?*

Estas mismas inquietudes me acompañaron cuando inicié mi camino en la programación, y, a decir verdad, aún me acompañan cuando busco bibliografía o recursos online en nuevas áreas de aprendizaje en donde requiero alguna solución de código.

Por eso, en este libro he optado por un enfoque centrado en la **resolución de tareas y problemas**. Así, el aprendizaje no solo se basa en ejecutar código, sino también en encontrar soluciones y responder preguntas reales que los estudiantes probablemente enfrentarán al momento de trabajar con datos reales. Muchos textos similares argumentan que la mejor manera de aprender a programar es simplemente programando. Si bien, personalmente comparto esta idea, estoy convencido de que ese camino se hace más efectivo cuando le encontramos un ***por qué*** o un ***para qué*** a nuestras acciones.

No es lo mismo aprender a programar con un dataset inventado o de *juguete* que uno con el que se puedan reproducir tablas y gráficos de informes oficiales que son el principal insumo para el análisis y toma de decisiones en materia de seguridad de un gobierno.

En un mundo donde la información abunda pero el tiempo escasea debido a nuestras múltiples responsabilidades laborales y personales, contar con un recurso que facilite resultados prácticos y aplicables es invaluable. Mi intención es que este material no solo sea útil en proyectos académicos, sino también en distintos entornos de trabajo, promoviendo soluciones eficientes y basadas en datos.

Así, este libro es el resultado de más de cinco años de aprendizaje adquirido a partir de mi interés en abordar desafíos laborales y de investigación. En el primer año en que aprendí a usar `R`, recuerdo las intensas horas de dedicación intentando solucionar errores a los que no lograba encontrar su origen. Sin duda, la curva de aprendizaje para alguien que no es programador es bastante inclinada y requiere de un tiempo importante de adaptación.

Pero como todas las disciplinas, la práctica permite sortear tales dificultades y afinar el *ojo* de los errores que, sin lugar a duda, ocurrirán en este camino de aprendizaje. Y ese proceso se hace mucho más llevadero si es que contamos con recursos que nos den luces sobre cómo enfrentar tales complicaciones.

De este modo, confío en que este material sirva a estudiantes, profesionales y futuros analistas interesados en aportar al bien común brindándoles herramientas útiles para tomar decisiones informadas y basadas en datos.

## Agradecimientos

Quiero agradecer a todas las personas que hicieron posible este proyecto. Son muchas, ya que cada experiencia e interacción ha enriquecido mi camino. Sin embargo, quisiera empezar por mi familia. Sin el apoyo incondicional de mis padres, el investigador curioso que soy hoy probablemente nunca habría existido. Su amor, su estímulo constante y su enseñanza para preocuparme por los demás y por aprender cosas nuevas son el núcleo de esta iniciativa.

A mi pareja, por su apoyo incondicional, quien siempre encuentra la manera de elevar mi ánimo y reforzar mi confianza cuando más lo necesito, además de generar en mi admiración por su talento y contribución las temáticas ligadas al desempleo nacional.

A mis jefaturas y compañeros de trabajo, especialmente aquellos del Departamento de Evaluación de Políticas Públicas de la Subsecretaría de Prevención del Delito: Cristian Crespo y Gabriel Moraga, quienes fueron fundamentales en mi formación como investigador.

A mis profesores del Diplomado en Ciencia de Datos para Políticas Públicas, del cual ahora soy parte como docente, y en particular a Pablo Aguirre, quien confió en mis capacidades y me dio la oportunidad de ser su ayudante; y hoy, poder realizar una versión renovada del curso que me inició en este mundo de la programación.

Y finalmente, a todas las personas que han dejado una huella positiva en mi vida, incluso con una breve conversación de pasillo. Cada una de ellas ha contribuido, de alguna manera, a que este proyecto sea una realidad.
